name: CI Build

on:
  push:
    branches:
    - main
    - develop

jobs:
  ci-build:
    uses: ./.github/workflows/01-ci-build.yml
    with:
      build-tool: 'maven' # or 'gradle'

  setup-deploy:
    needs: [ci-build]
    uses: ./.github/workflows/02-setup-deploy.yml

  publish-sonatype:
    needs: [setup-deploy]
    uses: ./.github/workflows/03-publish-sonatype.yml

  configure-aws:
    needs: [publish-sonatype]
    uses: ./.github/workflows/04-configure-aws.yml

  terraform:
    needs: [configure-aws]
    uses: ./.github/workflows/05-terraform.yml

  package-upload-s3:
    needs: [terraform]
    uses: ./.github/workflows/06-package-upload-s3.yml

  deploy-code-deploy:
    needs: [package-upload-s3]
    uses: ./.github/workflows/07-deploy-code-deploy.yml

  deploy-code-deploy-ec2:
    needs: [deploy-code-deploy]
    uses: ./.github/workflows/08-deploy-code-deploy-ec2.yml
